[build]
  functions = "netlify-functions"

[[redirects]]
  from = "/auth.html"
  to = "/auth.html"
  status = 200

[[redirects]]
  from = "/token.html"
  to = "/token.html"
  status = 200

[[redirects]]
  from = "/403.html"
  to = "/403.html"
  status = 200

[[redirects]]
  from = "/500.html"
  to = "/500.html"
  status = 200

[[redirects]]
  from = "/save-auth"
  to = "/.netlify/functions/TelegramAuth"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/GetPageContent"
  status = 200
  force = true

[[headers]]
  # Define which paths this specific [[headers]] block will cover.
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"