[build]
  functions = "netlify-functions"

[[redirects]]
  from = "/notes/*"
  to = "/.netlify/functions/GetPageContent"
  status = 200
  force = true

[[headers]]
  # Define which paths this specific [[headers]] block will cover.
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"